receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging: {}
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

extensions:
  health_check:
  pprof:
  zpages:

service:
  telemetry:
    logs:
      level: debug
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin,logging]
