# https://docs.docker.com/compose/compose-file/

x-common-variables: &common-variables
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=60.0
  SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  USERCTX_KEY: JWTSecretKeyDontUseInProduction!
  server.shutdown: graceful
  server.max-http-header-size: 64KB
  server.forward-headers-strategy: framework
  eureka.client.serviceUrl.defaultZone: http://registry:8080/eureka
  eureka.client.registry-fetch-interval-seconds: 15
  eureka.client.instance-info-replication-interval-seconds: 15
  eureka.client.healthcheck.enabled: true
  eureka.instance.non-secure-port: 8080
  eureka.instance.prefer-ip-address: true
  eureka.instance.initialStatus: STARTING
  management.endpoints.web.exposure.include: '*'
  management.endpoints.enabled-by-default: true
  management.security.roles: ANONYMOUS,ACTUATOR,USER
  spring.main.banner-mode: off
  spring.zipkin.enabled: false
  spring.cloud.config.enabled: false
  spring.cloud.kubernetes.enabled: false
  backbase.audit.enabled: false
  backbase.security.public.paths: /integration-api/**
  backbase.security.mtls.enabled: false
  backbase.http.request-logging-filter.max-payload-length: 5000
  logging.level.com.backbase: INFO
  logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

x-database-variables: &database-variables
  logging.level.liquibase: INFO
  spring.liquibase.enabled: true
  spring.datasource.username: root
  spring.datasource.password: root
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

x-message-broker-variables: &message-broker-variables
  spring.activemq.broker-url: tcp://activemq:61616
  spring.activemq.user: admin
  spring.activemq.password: admin

x-healthcheck-defaults: &healthcheck-defaults
  start_period: 60s
  interval: 15s
  timeout: 5s
  retries: 15

name: danske

volumes:
  danske_mysql_data:
    driver: local

networks:
  default:
    name: danske_default

services:
  mysql:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - danske_mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: symptoma/activemq:5.17.3
    privileged: true
    ports:
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      test: /opt/activemq/bin/activemq query --objname type=Broker,brokerName=*,service=Health | grep Good
      interval: 10s
      timeout: 5s
      retries: 5

  registry:
    container_name: registry
    image: repo.backbase.com/backbase-docker-releases/registry:${BB_VERSION}
    ports:
      - "8761:8080"
    volumes:
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java" ]

  edge:
    image: repo.backbase.com/backbase-docker-releases/edge:${BB_VERSION}
    ports:
      - "8280:8080"
    environment:
      <<: *common-variables
      gateway.actuator.security.enabled: false
      gateway.csrf.enabled: false
      "SPRING_APPLICATION_JSON": '{"spring":{"cloud":{"globalcors":{"corsConfigurations":{"[/**]":{"allowedOriginPatterns":"http://localhost:*","exposedHeaders":"*","allowedHeaders":"X-Requested-With,Origin,Content-Type,Accept,Authorization,x-xsrf-token,X-XSRF-TOKEN,x-total-count","allowedMethods":["GET","POST","OPTIONS","PUT","PATCH","DELETE"]}}}}}}'
    volumes:
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://registry:8080/eureka/apps/edge", "<status>UP</status>" ]
    links:
      - registry
      - token-converter

  token-converter:
    image: repo.backbase.com/backbase-docker-releases/oidc-token-converter-service:${BB_VERSION}
    ports:
      - "7779:8080"
    environment:
      <<: *common-variables
      backbase.oidc-token-converter.whitelistedDomains[0].internalHostScheme: http
      backbase.oidc-token-converter.whitelistedDomains[0].internalHost: backbase-identity:8080
      backbase.oidc-token-converter.whitelistedDomains[0].issuerHost: localhost
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/token-converter", "<status>UP</status>" ]
    links:
      - registry
      - backbase-identity

  backbase-identity:
    image: auth-server:${BB_VERSION}
    build:
      context: ../images/auth-server
      args:
        IDENTITY_BUILDER: repo.backbase.com/backbase-docker-releases/auth-server-builder:${BB_VERSION}
    ports:
      - '8180:8080'
    environment:
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_EXPOSED_HEADERS: "Location"
      QUARKUS_HTTP_CORS_ORIGINS: "http://localhost:8080,http://localhost:9090,http://localhost:4200,http://localhost:7070,http://localhost:6060"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB_URL: "jdbc:mysql://mysql:3306/backbase_identity?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true"
      KC_DB_USERNAME: "root"
      KC_DB_PASSWORD: "root"
      KC_LOG_LEVEL: "INFO"
      KC_LOG_CONSOLE_FORMAT: "%d{yyy:MM:dd HH:mm:ss.SSS} %-5p [%X{traceId},%X{spanId},%X{sampled}] %i --- [%t] %c{2.} : %m%n"
      KC_HOSTNAME_URL: "http://localhost:8180/auth/"
      KC_SPI_SERVICE_TOKEN_DEFAULT_URL: "http://token-converter:8080"
      KC_SPI_USER_MANAGER_CLIENT_DEFAULT_URL: "http://user-manager:8080"
      KC_SPI_CONNECTIONS_JPA_LEGACY_INITIALIZE_EMPTY: "true"
      KC_SPI_CONNECTIONS_JPA_LEGACY_MIGRATION_STRATEGY: "update"
      JAVA_TOOL_OPTIONS: "-Dquarkus.log.category.'\"com.backbase\"'.level=INFO \
                          -Dquarkus.log.category.'\"org.keycloak.protocol.oidc\"'.level=TRACE"
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://localhost:8080/auth/realms/backbase/.well-known/openid-configuration", "backbase" ]
    depends_on:
      mysql:
        condition: service_healthy

  access-control:
    image: repo.backbase.com/backbase-docker-releases/access-control:${BB_VERSION}
    ports:
      - "8040:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      spring.datasource.url: jdbc:mysql://mysql:3306/access-control?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      "backbase.data-group.types": "ARRANGEMENTS,CONTACTS,CUSTOMERS,PAYEES,REPOSITORIES,CUSTOM"
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/access-control", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  arrangement-manager:
    image: repo.backbase.com/backbase-docker-releases/arrangement-manager:${BB_VERSION}
    ports:
      - "8050:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      spring.datasource.url: jdbc:mysql://mysql:3306/arrangement-manager?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      logging.level.root: DEBUG
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/arrangement-manager", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  user-manager:
    image: repo.backbase.com/backbase-docker-releases/user-manager:${BB_VERSION}
    ports:
      - "8060:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      spring.datasource.url: jdbc:mysql://mysql:3306/user-manager?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      backbase.users.identity-endpoints-enabled: true
      backbase.users.identity-integration-enabled: true
      backbase.users.sync-primary-to-identity-enabled: true
      spring.cloud.discovery.client.simple.instances.user-integration-outbound-service[0].uri: http://wiremock:8080
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/user-manager", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  user-lifecycle:
    image: repo.backbase.com/backbase-docker-releases/user-lifecycle:${BB_VERSION}

    ports:
      - "8071:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      backbase_provision_config_realms_0_bank-external-id: "danske-bank-denmark"
      BACKBASE_PROVISION_CONFIG_REALMS_0_NAME: "customer"
      BACKBASE_PROVISION_CONFIG_REALMS_0_ASPECTS_CUSTOMER_0: "Retail User"
      logging.level.com.backbase: DEBUG
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/user-lifecycle", "<status>UP</status>" ]
    links:
      - registry
      - backbase-identity

  retail-onboarding:
    image: repo.backbase.com/backbase-docker-releases/retail-onboarding-service:2024.03-digital-sales
    ports:
      - "8091:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      spring.datasource.url: jdbc:mysql://mysql:3306/retail-onboarding?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_unicode_ci
      server.port: 8080
      "spring.application.name": "retail-onboarding"
      SPRING_PROFILES_ACTIVE: eureka,dbs-audit,dbs-entitlements,identity,cxs-cs
      "backbase.retail.url": "http://localhost:9090"
      "FLOW_NAME": "retail-onboarding"
      "backbase.flow.integrations.credential-creation.flow-config.flow-service-registry-name": "retail-onboarding"
      "backbase.flow.retail-onboarding.account-funding.internal-account.type": "CHECKING"
      "backbase.flow.retail-onboarding.account-funding.internal-account.number": "123213"
      "backbase.flow.retail-onboarding.account-funding.internal-account.routingNumber": "123213"
      "backbase.flow.retail-onboarding.account-funding.internal-account.nickname": "Citi Checking Account"
      "backbase.flow.retail-onboarding.account-funding.internal-account.code": "1"
      "backbase.flow.retail-onboarding.credentials-activation.realm": "customer"
      "backbase.flow.iam.dbs.externalLegalEntityId": "danske-bank-denmark"
      "backbase.flow.integrations.identity.password": "admin"
      "backbase.flow.integrations.identity.username": "admin"
      backbase.flow.integrations.credential-creation.flow-config.line-of-business: RETAIL
      #  Disabled connectors for Retail Onboarding
      "backbase.flow.integrations.global.mode": "mock"
      "backbase.flow.integrations.twilio.one-time-password.mode": "mock"
      "backbase.flow.integrations.payveris.account-funding.mode": "mock"
      "backbase.flow.integrations.yodlee.account-verification.client.clientId": "none"
      "backbase.flow.integrations.yodlee.account-verification.client.secret": "none"
      "backbase.flow.integrations.yodlee.account-verification.client.fastlinkUrl": "none"
      "backbase.flow.integrations.yodlee.account-verification.client.fastlinkConfigName": "none"
      "backbase.flow.integrations.yodlee.account-verification.client.serviceUrl": "none"
      "backbase.flow.integrations.yodlee.account-verification.client.apiVersion": "none"
      "backbase.flow.integrations.product-selection.file-config.image-url-prefix": "{BB_GATEWAY_URL}/retail-onboarding/assets/product-selection/"
      "backbase.flow.integrations.customer-and-account-creation.mode": "direct"
      logging.level.com.backbase: DEBUG
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: [*healthcheck-defaults]
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/retail-onboarding", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - registry
      - activemq

  party-profile:
    image: repo.backbase.com/backbase-docker-releases/party-profile-service:${ONBOARDING_VERSION}
    ports:
      - "8092:8080"
    environment:
      <<: [ *common-variables, *database-variables, *message-broker-variables ]
      spring.datasource.url: jdbc:mysql://mysql:3306/party-profile?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      SPRING_PROFILES_ACTIVE: eureka
      spring.application.name: party-profile
      server.port: 8080
      backbase.communication.services.integration.deposit-account.service-id: deposit-account-integration-service
      backbase.communication.services.integration.customer.service-id: customer-integration-service
      backbase.party-profile.customer.document-type: SOCIAL
      backbase.party-profile.deactivate-created-credentials: false
      backbase.party-profile.flow.customer.default-realm: customer
      backbase.party-profile.policies.configuration.prefix: policies/
      backbase.party-profile.policies.configuration.suffix: .json
      backbase.party-profile.policies.fallback: CaseInstanceReadOnly
      backbase.party-profile.policies.products.retail-loans: CaseInstanceDocumentUploadFullAccess
      backbase.party-profile.policies.products.unsecured-small-business-loans: CaseInstanceDocumentUploadFullAccess
      BACKBASE_PARTYPROFILE_FLOW_CUSTOMER_LINEOFBUSINESSES_0_NAME: "RETAIL"
      BACKBASE_PARTYPROFILE_FLOW_CUSTOMER_LINEOFBUSINESSES_0_REALMNAME: "customer"
      BACKBASE_PARTYPROFILE_FLOW_CUSTOMER_LINEOFBUSINESSES_0_PARENTLEGALENTITYID: "danske-bank-denmark"
      BACKBASE_PARTYPROFILE_PERMISSIONS_0_FUNCTIONID: "1028"
      BACKBASE_PARTYPROFILE_PERMISSIONS_0_BUSINESSFUNCTION: Manage Service Agreements
      BACKBASE_PARTYPROFILE_PERMISSIONS_0_PRIVILEGES_0: view
      BACKBASE_PARTYPROFILE_PERMISSIONS_1_FUNCTIONID: "1150"
      BACKBASE_PARTYPROFILE_PERMISSIONS_1_BUSINESSFUNCTION: "Manage Applications"
      BACKBASE_PARTYPROFILE_PERMISSIONS_1_PRIVILEGES_0: view
      logging.level.com.backbase: DEBUG
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/party-profile", "<status>UP</status>" ]
      disable: true
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - registry
      - activemq

  customer-integration-service:
    image: harbor.backbase.eu/development/customer-integration-outbound-mock:1.1.0
    ports:
      - "9367:8080"
    environment:
      <<: [ *common-variables, *database-variables, *message-broker-variables ]
      eureka.client.enabled: 'true'
      spring.application.name: 'customer-integration-service'
      backbase.security.public.paths: /service-api/**,/integration-api/**
      backbase.security.service.enabled: false
      logging.level.com.backbase: DEBUG
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/customer-integration-service", "<status>UP</status>" ]
    links:
      - registry
      - activemq

  deposit-account-integration-service:
    image: harbor.backbase.eu/development/deposit-account-integration-outbound-mock:latest

    ports:
      - "9366:8080"
    environment:
      <<: [ *common-variables, *database-variables, *message-broker-variables ]
      eureka.client.enabled: 'true'
      spring.application.name: 'deposit-account-integration-service'
      backbase.security.public.paths: /service-api/**,/integration-api/**
      backbase.security.service.enabled: false
      logging.level.com.backbase: DEBUG
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/deposit-account-integration-service", "<status>UP</status>" ]
    links:
      - registry
      - activemq

  identity-integration-service:
    image: repo.backbase.com/backbase-docker-releases/identity-integration-service:${BB_VERSION}
    ports:
      - "8070:8080"
    environment:
      <<: *common-variables
      identity.serverUrl: http://backbase-identity:8080/auth
      identity.masterAdmin.username: admin
      identity.masterAdmin.password: admin
      identity.realmConfiguration.fallbackOptions.enableUser: true
      identity.realmConfiguration.fallbackOptions.useTemporaryPassword: true
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/identity-integration-service", "<status>UP</status>" ]
    links:
      - registry
      - backbase-identity

  identity-proxy:
    image: repo.backbase.com/backbase-docker-releases/identity-proxy-service:${ONBOARDING_VERSION}

    ports:
      - "8098:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *message-broker-variables ]
      server.port: 8080
      "spring.application.name": "identity-proxy"
      backbase.security.public.paths: /client-api/**
      SPRING_PROFILES_ACTIVE: eureka
      BACKBASE_IDENTITYPROXYSERVICE_FLOW_CUSTOMER_LINESOFBUSINESS_0_NAME: "RETAIL"
      BACKBASE_IDENTITYPROXYSERVICE_FLOW_CUSTOMER_LINESOFBUSINESS_0_REALMNAME: "customer"
      #  TO BE REMOVED IN 2024.04
      BACKBASE_IDENTITYPROXYSERVICE_FLOW_CUSTOMER_LINEOFBUSINESSES_0_NAME: "RETAIL"
      BACKBASE_IDENTITYPROXYSERVICE_FLOW_CUSTOMER_LINEOFBUSINESSES_0_REALMNAME: "customer"
      "backbase.identity-proxy-service.flow.customer.default-realm": "customer"
      "backbase.identity-proxy-service.identity.password": "admin"
      "backbase.identity-proxy-service.identity.username": "admin"
      BACKBASE_IDENTITY_PROXY_SERVICE_IDENTITY_SERVER_URL: http://backbase-identity:8080/auth
      BACKBASE_IDENTITY_PROXY_SERVICE_SERVICE_API_GET_IDENTITY_SPECIFICATIONS_URL: http://backbase-identity:8080/auth/admin/realms/%s
      BACKBASE_IDENTITY_PROXY_SERVICE_SERVICE_API_PUT_RESET_PASSWORD_URL: http://backbase-identity:8080/auth/admin/realms/%s/users/%s/reset-password
      BACKBASE_IDENTITY_PROXY_SERVICE_SERVICE_API_GET_IDENTITY_TOKEN_URL: http://backbase-identity:8080/auth/realms/%s/protocol/openid-connect/token
      logging.level.com.backbase: TRACE
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/identity-proxy", "<status>UP</status>" ]
    links:
      - edge
      - registry
      - backbase-identity

  content-service:
    image: repo.backbase.com/backbase-docker-releases/contentservices:${BB_VERSION}

    ports:
      - "8097:8080"
    environment:
      <<: [ *common-variables, *database-variables, *message-broker-variables ]
      spring.datasource.url: jdbc:mysql://mysql:3306/content-service?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      "contentservices.storage.defaultImplementation": "DB"
      "contentservices.whitelist.allowedContentTypes": "image/jpeg,image/pjpeg,image/gif,image/png,image/svg+xml,application/pdf,application/json,application/zip,application/rtf,text/plain,text/html,text/csv,application/octet-stream,text/x-handlebars-template"
      "spring.cloud.azure.eventhubs.kafka.enabled": "false"
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/content-service", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - registry
      - backbase-identity

  application-management-service:
    image: repo.backbase.com/backbase-docker-releases/application-management-service:${BB_VERSION}
    environment:
      <<: [ *common-variables, *database-variables, *message-broker-variables ]
      spring.datasource.url: jdbc:mysql://mysql:3306/application-management-service?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      BACKBASE_LENDING_DOCUMENTATION_SWAGGER_OPENIDCONNECTURL: http://backbase-identity:8080/auth/realms/employee/.well-known/openid-configuration
      BACKBASE_LENDING_DOCUMENTATION_SWAGGER_BASEAPIPATH: http://edge:8080/api/application-management-service
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dbs-audit,dbs-entitlements,identity
      spring.application.name: application-management-service
    volumes:
      - ./scripts:/tmp/h
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/application-management-service", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - registry
      - backbase-identity
      - edge

  product-catalog-task:
    image: repo.backbase.com/backbase-stream-images/product-catalog-task:${STREAM_VERSION}
    profiles:
      - stream-bootstrap
    environment:
      <<: *common-variables
      spring.config.additional-location: file:/tmp/ingestion.yml
    volumes:
      - ../config/stream/ingestion.yml:/tmp/ingestion.yml
    depends_on:
      token-converter:
        condition: service_healthy
      arrangement-manager:
        condition: service_healthy

  legal-entity-bootstrap-task:
    image: repo.backbase.com/backbase-stream-images/legal-entity-bootstrap-task:${STREAM_VERSION}
    profiles:
      - stream-bootstrap
    environment:
      <<: *common-variables
      spring.config.additional-location: file:/tmp/ingestion.yml
    volumes:
      - ../config/stream/ingestion.yml:/tmp/ingestion.yml
    depends_on:
      token-converter:
        condition: service_healthy
      access-control:
        condition: service_healthy
      arrangement-manager:
        condition: service_healthy
      user-manager:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      backbase-identity:
        condition: service_healthy
      product-catalog-task:
        condition: service_completed_successfully

  backbase-bootstrap-task:
    image: repo.backbase.com/backbase-bootstrap-task:0.29.0-SNAPSHOT-7
    profiles:
      - backbase-bootstrap
    environment:
      <<: [ *common-variables, *message-broker-variables ]
      "backbase.stream.limits.worker.enabled": "false"
      environment.installation: ""
      environment.runtime: ""
      "LOGGING_LEVEL_COM_BACKBASE": "DEBUG"
      # Enable/Disable product catalog ingestion
      "backbase.stream.bootstrap.product-catalog.bootstrapResourcesEnabled": "true"
      "backbase.stream.bootstrap.product-catalog.location": "file:/tmp/product-catalog.yml"
      #Enable/Disable LE ingestion
      "backbase.stream.bootstrap.legal-entity.bootstrapResourcesEnabled": "true"
      "backbase.stream.bootstrap.legal-entity.location": "file:/tmp/base-legal-entity.yml"
      # Admin Password override Enable/Disable
      "admin.bootstrapManualStepsEnabled": "true"
      "admin.baseUrl": "http://backbase-identity:8080/auth"
      "admin.username": "admin"
      "admin.password": "admin"
      "admin.defaultUserPassword": "Pass1234"
    volumes:
      - ../config/stream/product-catalog.yml:/tmp/product-catalog.yml
      - ../config/stream/base-legal-entity.yml:/tmp/base-legal-entity.yml
    depends_on:
      token-converter:
        condition: service_healthy
      access-control:
        condition: service_healthy
      arrangement-manager:
        condition: service_healthy
      user-manager:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      backbase-identity:
        condition: service_healthy
    links:
      - activemq
      - registry
      - backbase-identity

  wiremock:
    image: wiremock/wiremock:2.32.0
    profiles:
      - with-mocks
    command:
      - --global-response-templating
      - --verbose
    volumes:
      - ./stubs:/home/wiremock

  postman-health-check:
    image: postman/newman
    platform: linux/amd64
    command:
      run /etc/newman/postman_collection.json --environment="/etc/newman/postman_environment.json"
    volumes:
      -  ../../test/postman/HealthCheck_Local-Backend-Environment.postman_collection.json:/etc/newman/postman_collection.json
      -  ../../test/postman/Docker-Backend-Environment.postman_environment.json:/etc/newman/postman_environment.json
    depends_on:
      access-control:
        condition: service_healthy
      arrangement-manager:
        condition: service_healthy
      backbase-identity:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      token-converter:
        condition: service_healthy
      user-manager:
        condition: service_healthy

  retail-onboarding-prospect:
    image: repo.backbase.com/backbase-docker-releases/retail-onboarding-prospect:${ONBOARDING_VERSION}
    environment:
      FLOW_NAME: "retail-onboarding"
      "BASE_HREF": "/retail-onboarding/"
      PATHNAME: "/"
      PORT: 7070
      API_SERVICE_NAME: "retail-onboarding"
      API_ROOT: /api/
    ports:
      - "7070:7070"
    volumes:
      - ./nginx/api.conf:/nginx-config/server/15-api.conf
    healthcheck:
      test: [ "CMD", "none" ]
      disable: true
    links:
      - edge

  employee-app:
    image: crreference914.azurecr.io/web-employee-portalless-retail:${EMPLOYEE_APP_VERSION}
    environment:
      PORT: 8080
      AUTH_URL: http://localhost:8180/auth/
      API_ROOT: http://localhost:8080/api
      AUTH_REALM: "employee"
      AUTH_SCOPE: openids
      AUTH_CLIENT_ID: bb-web-client
      AUTH_LANDING_PAGE: select-context
      AUTH_REDIRECT_PAGE: redirect
      RO_SERVICE_NAME: retail-onboarding
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/api.conf:/nginx-config/server/15-api.conf
    healthcheck:
      test: [ "CMD", "none" ]
      disable: true
    links:
      - edge
      - backbase-identity

  retail-app:
    image: crreference914.azurecr.io/retail-usa:${RETAIL_APP_VERSION}
    environment:
      AUTH_URL: http://localhost:8180/auth/
      PORT: 9090
      "API_ROOT": /api/
      "AUTH_CLIENT_ID": "bb-web-client"
      "AUTH_LANDING_PAGE": "select-context"
      "AUTH_REALM": "customer"
      "AUTH_REDIRECT_PAGE": "redirect"
      "AUTH_SCOPE": "openid"
      "BASE_HREF": /
    ports:
      - "9090:9090"
    volumes:
      - ./nginx/api.conf:/nginx-config/server/15-api.conf
    healthcheck:
      test: [ "CMD", "none" ]
      disable: true
    links:
      - edge

  application-center:
    image: repo.backbase.com/backbase-docker-releases/application-center-ang:1.0.1
    environment:
      PORT: 6060
      AUTH_CLIENT_ID: "bb-web-client"
      AUTH_REALM: "customer"
      BASE_DOMAIN: http://localhost:6060
      API_ROOT: /api/
      AUTH_URL: http://localhost:8180/auth
      BASE_HREF: /application-center/
      #HOSTNAME:
      PROTOCOL: "http:"
    ports:
      - "6060:6060"
    volumes:
      - ./nginx/api.conf:/nginx-config/server/15-api.conf
    healthcheck:
      test: [ "CMD", "none" ]
      disable: true
    links:
      - edge


  #  remote-config:
#    image: repo.backbase.com/backbase-docker-releases/remote-config:2024.03-LTS
#    ports:
#      - "8097:8080"
#    environment:
#      <<: [*common-variables, *database-variables, *message-broker-variables]
#      spring.datasource.url: jdbc:mysql://mysql:3306/remote-config?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
#      "backbase.access-control.enabled": "true"
#      "backbase.audit.enabled": "true"
#      "backbase.remote-config.features.configuration-drafts": "true"
#      "spring.autoconfigure.exclude": ""
#      "spring.cloud.features.enabled": "false"
#      "spring.cloud.azure.eventhubs.kafka.enabled": "false"
#    volumes:
#      - ./scripts:/tmp/h
#    healthcheck:
#      <<: *healthcheck-defaults
#      test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/remote-config", "<status>UP</status>" ]
#    links:
#      - registry
#      - backbase-identity

  # <EXAMPLE-SERVICE-NAME>:
  #   image: <DOCKER-REGISTRY>/<REPOSITORY-NAME>:<TAG>
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     <<: *common-variables
  #     eureka.client.enabled: 'true'
  #   volumes:
  #     - ./scripts:/tmp/h
  #   healthcheck:
  #     <<: *healthcheck-defaults
  #     test: [ "CMD", "java", "/tmp/h/HealthCheck.java", "http://registry:8080/eureka/apps/<EXAMPLE-SERVICE-NAME>", "<status>UP</status>" ]
  #   links:
  #     - registry
