# https://docs.docker.com/compose/compose-file/

x-common-variables: &common-variables
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=60.0
  USERCTX_KEY: JWTSecretKeyDontUseInProduction!
  sso.jwt.internal.signature.key.type: VALUE
  sso.jwt.internal.signature.key.value: JWTSecretKeyDontUseInProduction!
  server.shutdown: graceful
  server.max-http-header-size: 64KB
  server.forward-headers-strategy: framework
  eureka.client.enabled: true
  eureka.client.serviceUrl.defaultZone: http://registry:8080/eureka
  eureka.client.registry-fetch-interval-seconds: 15
  eureka.client.instance-info-replication-interval-seconds: 15
  eureka.client.healthcheck.enabled: true
  eureka.instance.non-secure-port: 8080
  eureka.instance.prefer-ip-address: true
  eureka.instance.initialStatus: STARTING
  management.endpoints.web.exposure.include: '*'
  management.endpoints.enabled-by-default: true
  management.security.roles: ANONYMOUS,ACTUATOR
  management.endpoint.env.show-values: ALWAYS
  management.endpoint.env.post.enabled: true
  management.endpoint.configprops.show-values: ALWAYS
  spring.main.banner-mode: off
  spring.cloud.config.enabled: false
  spring.cloud.kubernetes.enabled: false
  backbase.audit.enabled: true
  backbase.security.public.paths: /integration-api/**
  backbase.security.mtls.enabled: false
  backbase.http.request-logging-filter.max-payload-length: 5000
  logging.level.com.backbase: DEBUG
  logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  # Observability - Tracing Configuration
  management.tracing.enabled: false
  management.tracing.propagation.type: w3c
  management.tracing.sampling.probability: 1.0
  management.tracing.baggage.remote-fields: client-id
  management.tracing.baggage.correlation.fields: client-id
  #  management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
  spring.autoconfigure.exclude: org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration
  management.otlp.tracing.endpoint: http://otel-collector:4318/v1/traces

x-database-variables: &database-variables
  logging.level.liquibase: INFO
  spring.liquibase.enabled: true
  spring.datasource.username: root
  spring.datasource.password: root
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

x-message-broker-variables: &message-broker-variables
  spring.activemq.broker-url: tcp://activemq:61616
  spring.activemq.user: admin
  spring.activemq.password: admin

x-healthcheck-defaults: &healthcheck-defaults
  start_period: 60s
  interval: 15s
  timeout: 3s
  retries: 15

x-gc-api-config: &gc-api-config
  "BACKBASE_GC_API-CONFIG_DEPOSIT-API.PAYMENT-ACCOUNT-TYPE": "DEPOSIT"
  "BACKBASE_GC_API-CONFIG_DEPOSIT-API_SUPPORTED-PRODUCT-KINDS_0": "kind1"
  "BACKBASE_GC_API-CONFIG_DEPOSIT-API_SUPPORTED-PRODUCT-KINDS_1": "kind2"
  "BACKBASE_GC_API-CONFIG_DEPOSIT-API_SUPPORTED-PRODUCT-KINDS_2": "kind6"
  "BACKBASE_GC_API-CONFIG_DEPOSIT-API_SUPPORTED-PRODUCT-KINDS_3": "kind8"
  "BACKBASE_GC_API-CONFIG_DEPOSIT-API_SUPPORTED-PRODUCT-KINDS_4": "kind9"
  "BACKBASE_GC_API-CONFIG_LOAN-API.PAYMENT-ACCOUNT-TYPE": "LOAN"
  "BACKBASE_GC_API-CONFIG_LOAN-API_SUPPORTED-PRODUCT-KINDS_0": "kind4"
  "BACKBASE_GC_API-CONFIG_LOAN-API_SUPPORTED-PRODUCT-KINDS_1": "kind5"

x-gc-http-config: &gc-http-config
  "backbase.gc.http.readTimeout": "0"
  "backbase.gc.http.connectTimeout": "0"
  "backbase.gc.http.retryCount": "1"
  "backbase.gc.http.backoff": "1000"

x-gc-credentials: &gc-credentials
  backbase.gc.party-base-url: "http://caboose:8080"
  backbase.gc.payment-base-url: "http://caboose:8080"
  backbase.gc.deposit-base-url: "http://caboose:8080"
  backbase.gc.loan-base-url: "http://caboose:8080"
  backbase.gc.subscriptionKey: ""

name: backbase

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:8.4.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: apache/activemq-classic
    ports:
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      test: activemq status
      interval: 10s
      timeout: 5s
      retries: 5
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    profiles:
      - tracing-tools
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    restart: always
    profiles:
      - tracing-tools
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./docker/collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - zipkin
  registry:
    image: repo.backbase.com/backbase-docker-releases/registry:${BB_VERSION}
    ports:
      - "8761:8080"
    environment:
      management.tracing.enabled: false
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar" ]

  edge:
    image: repo.backbase.com/backbase-docker-releases/edge:${BB_VERSION}
    ports:
      - "8280:8080"
    environment:
      <<: *common-variables
      spring.application.name: "edge"
      gateway.actuator.security.enabled: false
      gateway.csrf.enabled: false
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    links:
      - registry

  token-converter:
    image: repo.backbase.com/backbase-docker-releases/oidc-token-converter-service:${BB_VERSION}
    ports:
      - "7779:8080"
    environment:
      <<: *common-variables
      spring.application.name: "token-converter"
      backbase.security.public.paths: /oauth/token,/convert
      backbase.oidc-token-converter.whitelistedDomains[0].internalHostScheme: http
      backbase.oidc-token-converter.whitelistedDomains[0].internalHost: backbase-identity:8080
      backbase.oidc-token-converter.whitelistedDomains[0].issuerHost: localhost
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    links:
      - registry

  backbase-identity:
    image: repo.backbase.com/backbase-docker-releases/auth-server-builder:2025.03-LTS
    entrypoint: /opt/keycloak/bin/auth-server-buildconfig-and-run.sh
    command:
      - start-dev
      - --import-realm
    ports:
      - '8180:8080'
    environment:
      <<: [ *common-variables, *message-broker-variables, *gc-credentials, *gc-api-config, *gc-http-config]
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      BACKBASE_HTTP_CORS: "true"
      BACKBASE_HTTP_CORS_EXPOSED_HEADERS: "Location"
      BACKBASE_HTTP_CORS_ORIGINS: "http://localhost:4200,http://localhost:8080"
      KC_DB: "mysql"
      KC_DB_URL: "jdbc:mysql://mysql:3306/backbase_identity?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true"
      KC_DB_USERNAME: "root"
      KC_DB_PASSWORD: "root"
      KC_TRANSACTION_XA_ENABLED: "true"
      KC_LOG_LEVEL: "INFO"
      backbase.audit.enabled: true
      KC_LOG_CONSOLE_FORMAT: "%d{yyy:MM:dd HH:mm:ss.SSS} %-5p [%X{traceId},%X{spanId},%X{sampled}] %i --- [%t] %c{2.} : %m%n"
      KC_HOSTNAME_URL: "http://localhost:8180/auth/"
      KC_SPI_SERVICE_TOKEN_DEFAULT_URL: "http://token-converter:8080"
      KC_SPI_USER_MANAGER_CLIENT_DEFAULT_URL: "http://user-manager:8080"
      KC_SPI_CONNECTIONS_JPA_LEGACY_INITIALIZE_EMPTY: "true"
      KC_SPI_CONNECTIONS_JPA_LEGACY_MIGRATION_STRATEGY: "update"
      keycloak.backbase.event-listeners.audit.endpoint: "http://audit-service:8080"
      KC_SPI_EVENTS_LISTENER_AUDIT_INTEGRATION_SERVICE_URL: "http://audit-service:8080"
      KC_SPI_EVENTS_LISTENER_EVENT_BRIDGE_AUDIT_NO_AUTH_LOCALHOST: "true"
      KC_SPI_EVENTS_LISTENER_EVENT_BRIDGE_AUDIT_URL: "http://localhost:8090"
    #  KC_SPI_MOBILE_AUTHENTICATION_CLIENT_DEFAULT_URL: "http://mobile-authentication:8080"
      JAVA_TOOL_OPTIONS: "-Dquarkus.log.category.'\"com.backbase\"'.level=DEBUG \
                          -Dquarkus.log.category.'\"org.keycloak.protocol.oidc\"'.level=TRACE"
    volumes:
      - ./identity:/opt/keycloak/data/import
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/auth/realms/backbase/.well-known/openid-configuration", "backbase" ]
    depends_on:
      mysql:
        condition: service_healthy

  access-control:
    image: repo.backbase.com/backbase-docker-releases/access-control:${BB_VERSION}
    ports:
      - "8040:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      spring.application.name: "access-control"
      spring.datasource.url: jdbc:mysql://mysql:3306/access-control?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  arrangement-integration:
    image: repo.backbase.com/backbase-docker-releases/arrangement-integration:${BB_VERSION}
    ports:
      - "9050:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *gc-credentials, *gc-api-config, *gc-http-config]
      eureka.instance.appname: arrangement-integration
      logging.level.root: INFO
      logging.level.org.springframework.web.client.RestTemplate: INFO
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  arrangement-manager:
    image: repo.backbase.com/backbase-docker-releases/arrangement-manager:${BB_VERSION}
    ports:
      - "8050:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
#      backbase.arrangement.arrangement-views.views: arrangement-views
      backbase.communication.services.account.integration.serviceId: "arrangement-integration"
      backbase.integration.outbound.pull-latest-balance: true
      backbase.arrangement.product-kinds.use-db: false
      backbase.arrangement.product-kinds.kinds.kind10.name: Investment Portfolio
      backbase.arrangement.product-kinds.kinds.kind10.id: 10
      backbase.arrangement.product-kinds.kinds.kind10.uri: investment-portfolio
      backbase.arrangement.product-kinds.kinds.kind10.custom-order: 10
      backbase.arrangement.product-kinds.kinds.kind10.balance-aggregation-amount: current-investment-value
      backbase.arrangement.product-kinds.kinds.kind10.translations.locale: en
      backbase.arrangement.product-kinds.kinds.kind10.translations.localeTranslations.fieldName: kind_name
      backbase.arrangement.product-kinds.kinds.kind10.translations.localeTranslations.fieldValue: Investment Portfolio
      backbase.arrangement.product-kinds.kinds.kind11.name: ACH Company
      backbase.arrangement.product-kinds.kinds.kind11.id: 11
      backbase.arrangement.product-kinds.kinds.kind11.uri: ach-company
      backbase.arrangement.product-kinds.kinds.kind11.custom-order: 11
      backbase.arrangement.product-kinds.kinds.kind11.balance-aggregation-amount: current-investment-value
      backbase.arrangement.product-kinds.kinds.kind11.translations.locale: en
      backbase.arrangement.product-kinds.kinds.kind11.translations.localeTranslations.fieldName: kind_name
      backbase.arrangement.product-kinds.kinds.kind11.translations.localeTranslations.fieldValue: ACH Company
      spring.application.name: "arrangement-manager"
      spring.datasource.url: jdbc:mysql://mysql:3306/arrangement-manager?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      SPRING_CONFIG_ADDITIONAL_LOCATION: /tmp/application.yml
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
      - ./arrangement-manager/application.yml:/tmp/application.yml
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  loan-integration-outbound-mock:
    image: repo.backbase.com/backbase-docker-releases/loan-integration-outbound-mock:${BB_VERSION}
    ports:
      - "9055:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *gc-credentials, *gc-api-config, *gc-http-config ]
      eureka.instance.appname: loan-integration-outbound-mock
      logging.level.root: INFO
      logging.level.org.springframework.web.client.RestTemplate: INFO
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

#  loan-integration:
#    image: repo.backbase.com/backbase-docker-releases/loan-integration:${BB_VERSION}
#    ports:
#      - "9054:8080"
#    environment:
#      <<: [ *common-variables, *message-broker-variables, *gc-credentials, *gc-api-config, *gc-http-config]
#      eureka.instance.appname: loan-integration
#      logging.level.root: INFO
#      logging.level.org.springframework.web.client.RestTemplate: INFO
#    volumes:
#      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
#    healthcheck:
#      <<: *healthcheck-defaults
#      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
#    depends_on:
#      mysql:
#        condition: service_healthy
#    links:
#      - activemq
#      - registry

  loan:
    image: repo.backbase.com/backbase-docker-releases/loan:${BB_VERSION}
    ports:
      - "8054:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      #      backbase.arrangement.arrangement-views.views: arrangement-views
      backbase.communication.services.dbs.loan.integration.outbound.service-id: "loan-integration-outbound-mock"
      spring.application.name: "loan"
      spring.datasource.url: jdbc:mysql://mysql:3306/loan?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      backbase.arrangement.alias.journey: "USER_ALIAS"
      spring.cloud.azure.eventhubs.kafka.enabled: "false"
      backbase.loan.payments.payment-option-validation-on-core-banking: "false"
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  transaction-manager:
    image: repo.backbase.com/backbase-docker-releases/transaction-manager:2025.08.5
    ports:
      - "8052:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *database-variables ]
      spring.datasource.url: jdbc:mysql://mysql:3306/transaction-manager?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      "backbase.communication.http.autowire-object-mapper": "true"
      "backbase.security.csrf.enabled": "false"
      "backbase.security.mtls.enabled": "false"
      "backbase.transaction.enrichment.enabled": "false"
      "backbase.transaction.refresh.triggers.payment.enabled": "true"
      "backbase.transaction.refresh.pull.daysRefreshWindow": "0"
      "backbase.transaction.csv.export.dateFormat": "MM/dd/YYYY"
      "backbase.transaction.csv.export.fields": "BBAN,name,counterPartyAccountNumber,counterPartyName,currency,amount,creditDebitIndicator,bookingDate,type,typeGroup,reference,instructedCurrency,currencyExchangeRate,instructedAmount,description,category,checkSerialNumber"
      "backbase.transaction.csv.export.headers": "Account number(BBAN),Account name,Counter party account number,Counter party name,Currency,Amount,Credit/debit indicator,Book date,Transaction type,Transaction group,Transaction reference,Instructed currency,currency exchange rate,Instructed amount,Description,Category,Check number"
      "backbase.transaction.pdf.export.maxItems": "10000"
      "backbase.communication.services.integration.transaction.external.pull.service-id": "transaction-integration"
      "backbase.pfm.common.base-currency": "USD"
      "backbase.transaction.refresh.pull.defaultRefreshDate": "2025-01-01"
      "backbase.communication.services.integration.transaction.external.pull.version": "v3"
      "backbase.transaction.domain.types": "PAY"
      "backbase.transaction.domain.typeGroups": "PAY"
      "backbase.transaction.domain.typeGroupMapping.PAY": "PAY"
      "backbase.communication.services.transaction.enrichment.version": "v1"
      "backbase.lifecycle.delayed-shutdown.delay": "15s"
      "backbase.lifecycle.delayed-shutdown.enabled": "true"
      "backbase.tailored-value-proposition.enabled": "true"
      "backbase.transaction.domain.typeGroupMapping.Fees": "Fee, Cheques"
      "backbase.transaction.domain.typeGroupMapping.Loans": "Deposit, ACH"
      "backbase.transaction.domain.typeGroupMapping.Other": "Other"
      "backbase.transaction.domain.typeGroupMapping.Payment": "Credit/Debit Card, Bill Payment"
      "backbase.transaction.domain.typeGroupMapping.Withdrawal": "ATM, Cash, POS, Withdrawal"
      "backbase.transaction.export.csv.dateFormat": "MM/dd/YYYY"
      "backbase.transaction.export.csv.fields": "BBAN,name,counterPartyAccountNumber,counterPartyName,currency,amount,creditDebitIndicator,bookingDate,type,typeGroup,reference,instructedCurrency,currencyExchangeRate,instructedAmount,description,category,checkSerialNumber"
      "backbase.transaction.export.csv.headers": "Account number(BBAN),Account name,Counter party account number,Counter party name,Currency,Amount,Credit/debit indicator,Book date,Transaction type,Transaction group,Transaction reference,Instructed currency,currency exchange rate,Instructed amount,Description,Category,Check number"
      "backbase.transaction.export.ofx.supportedProductTypes": "current-account,savings-account,loan,debit-card,credit-card"
      "backbase.transaction.export.pdf.maxItems": "10000"
      "backbase.transaction.export.qbo.supportedProductTypes": "current-account,savings-account,loan,debit-card,credit-card"
      "backbase.transaction.export.qfx.supportedProductTypes": "current-account,savings-account,loan,debit-card,credit-card"
      "backbase.transaction.partition.bookingDateSearchMaxDateRange": "91"

    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  transaction-integration:
    image: repo.backbase.com/backbase-docker-releases/transaction-integration:2025.08.5
    ports:
      - "9051:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *gc-credentials, *gc-api-config, *gc-http-config]
      eureka.instance.appname: transaction-integration
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  payment-order-service:
    image: repo.backbase.com/backbase-docker-releases/payment-order-service:${BB_VERSION}
    ports:
      - "8053:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *database-variables ]
      spring.datasource.url: jdbc:mysql://mysql:3306/payment-order-service?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      "backbase.communication.http.autowire-object-mapper": "true"
      "backbase.communication.services.dbs.integration.external.outbound.paymentorder.serviceId": "payment-integration"
      "backbase.security.csrf.enabled": "false"
      "backbase.security.mtls.enabled": "false"
      "backbase.payments.types": "INTERNAL_TRANSFER"
      "backbase.payments.types.INTERNAL_TRANSFER.business-function": "A2A Transfer"
      "backbase.payments.types.INTERNAL_TRANSFER.confirmation.enabled": "false"
      "backbase.payments.limits.enabled": false
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  payment-integration:
    image: repo.backbase.com/backbase-docker-releases/payment-integration:${BB_VERSION}
    ports:
      - "9061:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *gc-credentials, *gc-api-config, *gc-http-config]
      server.port: 8080
      eureka.instance.appname: payment-integration
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  user-manager:
    image: repo.backbase.com/backbase-docker-releases/user-manager:${BB_VERSION}
    ports:
      - "8060:8080"
    environment:
      <<: [*common-variables, *message-broker-variables, *database-variables]
      spring.application.name: "user-manager"
      spring.datasource.url: jdbc:mysql://mysql:3306/user-manager?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      backbase.users.identity-endpoints-enabled: true
      backbase.users.identity-integration-enabled: true
      backbase.users.sync-primary-to-identity-enabled: true
      spring.cloud.discovery.client.simple.instances.user-integration-outbound-service[0].uri: http://wiremock:8080
      backbase.users.realms[0].realm-name: "employee"
      backbase.users.realms[1].realm-name: "retail"
      backbase.users.realms[2].realm-name: "business"
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  identity-integration-service:
    image: repo.backbase.com/backbase-docker-releases/identity-integration-service:${BB_VERSION}
    ports:
      - "8070:8080"
    environment:
      <<: *common-variables
      identity.serverUrl: http://backbase-identity:8080/auth
      identity.masterAdmin.username: admin
      identity.masterAdmin.password: admin
      identity.realmConfiguration.fallbackOptions.enableUser: true
      identity.realmConfiguration.fallbackOptions.useTemporaryPassword: false
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    links:
      - registry

  bootstrap-job:
    image: bootstrap-job/development/bootstrap-job:20251007
    profiles:
      - bootstrap
    environment:
      <<: *common-variables
      backbase.bootstrap.data.active-data-sets: minimal-base
      backbase.bootstrap.identity.admin-realm: employee
      backbase.bootstrap.identity.admin-username: admin
      backbase.bootstrap.identity.master-admin-password: admin
      backbase.bootstrap.identity.default-admin-password: admin
      backbase.bootstrap.identity.defaultUserPassword: Pass1234
      backbase.bootstrap.identity.realms: employee,business,retail
      backbase.bootstrap.ingestions.messages.enabled: false
      backbase.bootstrap.ingestions.push-integration.enabled: false
      backbase.bootstrap.ingestions.permissionSet.enabled: true
      backbase.bootstrap.ingestions.global-limits.enabled: false
      backbase.bootstrap.ingestions.fido-applications.enabled: false
      backbase.bootstrap.ingestions.content-repository.enabled: false
      backbase.bootstrap.ingestions.wealth.enabled: false
      backbase.bootstrap.ingestions.approvals.enabled: false
      backbase.bootstrap.ingestions.regions.enabled: false
      backbase.bootstrap.ingestions.cards: false
      caboose.baseUrl: "http://caboose-spring:8080"
      backbase.communication.services.access-control.directUri: http://access-control:8080
      backbase.communication.services.limit.directUri: http://limits-service:8080
      backbase.communication.services.usermanager.directUri: http://user-manager:8080
      backbase.communication.services.identity.integration.directUri: http://identity-integration-service:8080
      spring.security.oauth2.client.provider.bb.token-uri: http://token-converter:8080/oauth/token
      backbase.communication.http.access-token-uri: http://token-converter:8080/oauth/token
      admin.baseUrl: http://backbase-identity:8080
      backbase.communication.services.arrangement.manager.directUri: http://arrangement-manager:8080
      backbase.bootstrap.identity.baseUrl: http://backbase-identity:8080/auth
      spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
    #Marqeta related settings. SET below value to true to enable marqeta ingestion
      "backbase.bootstrap.ingestions.plugins.marqeta.enabled": "false"
      "backbase.bootstrap.ingestions.plugins.marqeta.username": "a6af7aec-c973-461d-8044-67c25e7af1f0"
      "backbase.bootstrap.ingestions.plugins.marqeta.password": "59301adf-7a6b-43b1-95ee-99d7408a3754"
      "backbase.bootstrap.ingestions.plugins.marqeta.baseUrl": "https://sandbox-api.marqeta.com/v3"
      "backbase.bootstrap.ingestions.plugins.marqeta.imageBaseUrl": "http://cards-assets-management:4300/assets/"
      "backbase.bootstrap.data.legal-entity-prefix.enabled": "false"
      backbase.bootstrap.ingestions.plugins.marqeta.debugEnabled: true
      #Permission set related DB settings
      backbase.bootstrap.ingestions.permissionSet.datasource.username: "root"
      backbase.bootstrap.ingestions.permissionSet.datasource.password: "root"
      backbase.bootstrap.ingestions.permissionSet.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"
      backbase.bootstrap.ingestions.permissionSet.datasource.url: "jdbc:mysql://mysql:3306/access-control?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true"
      backbase.bootstrap.ingestions.permissionSet.database-update.enabled: true
      backbase.bootstrap.ingestions.plugins.mambu.enabled: false
      backbase.bootstrap.ingestions.plugins.caboose.enabled: true
      backbase.stream.audiences.segmentation.user-kind.defaultCustomerCategory: RETAIL
      logging.level.com.backbase.bootstrap: DEBUG
      caboose.currentAccountProductKeys.USD: pr-current-account-usd
      caboose.currentAccountProductKeys.EUR: pr-current-account-eur
      caboose.savingsAccountProductKeys.USD: pr-saving-account-usd
      caboose.savingsAccountProductKeys.EUR: pr-saving-account-eur
      caboose.line-of-credit-product-keys.USD: pr-saving-account-usd
      caboose.line-of-credit-product-keys.EUR: pr-saving-account-eur
      caboose.term-loan-product-keys.USD: pr-term-loan-usd
      caboose.term-loan-product-keys.EUR: pr-term-loan-eur
      caboose.mortgage-product-keys.USD: pr-mortgage-usd
      caboose.mortgage-product-keys.EUR: pr-mortgage-eur
#    volumes:
#      # example where you can test your own files
#      - ./test-data/products-jh.json:/app/resources/modelbank/core-data/base/product-catalog/products-jh.json
    depends_on:
      token-converter:
        condition: service_healthy
      access-control:
        condition: service_healthy
      arrangement-manager:
        condition: service_healthy
      user-manager:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      backbase-identity:
        condition: service_healthy
      caboose:
        condition: service_healthy

  caboose:
    image: caboose-spring/development/caboose-spring:202510074
    ports:
      - "9001:8080"
    environment:
      <<: [*common-variables]
      SPRING_PROFILES_ACTIVE: local
      server.port: 8080

    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]

  # Newly added minimal mobile-authentication service (converted from K8s deployment)
#  mobile-authentication:
#    image: repo.backbase.com/backbase-docker-releases/mobile-authentication:2025.08.5
#    ports:
#      - "9080:8080"
#    environment:
#      <<: *common-variables
#      BACKBASE_SECURITY_CSRF_ENABLED: "false"
#      BUILDINGBLOCKS_SECURITY_CSRF_ENABLED: "false"
#      EUREKA_CLIENT_ENABLED: "false"
#      SPRING_LIQUIBASE_ENABLED: "false"
#      SPRING_PROFILES_INCLUDE: json-logging
#      SERVER_SHUTDOWN: graceful
#      LOGGING_LEVEL_ROOT: INFO
#      LOGGING_LEVEL_COM_BACKBASE: INFO
#      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=60.0 -Djava.security.egd=file:/dev/urandom"

  event-listener-service:
    image: repo.backbase.com/backbase-docker-releases/event-listener-service:2023.01.1-0.27.0-RC2
    ports:
      - "9082:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *database-variables ]
      BACKBASE_SECURITY_CSRF_ENABLED: "false"
      BUILDINGBLOCKS_SECURITY_CSRF_ENABLED: "false"
      LOGGING_LEVEL_COM_BACKBASE: "DEBUG"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "WARN"
      LOGGING_LEVEL_ROOT: "WARN"
      SERVER_SHUTDOWN: "graceful"
      SPRING_PROFILES_INCLUDE: "json-logging"
      backbase.events.enabled: "true"
      logging.level.com.backbase.buildingblocks.backend.security.auth.config.MtlsAuthenticationFilter: "WARN"
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  audit-service:
    image: repo.backbase.com/backbase-docker-releases/audit-service:${BB_VERSION}
    ports:
      - "9081:8080"
    environment:
      <<: [ *common-variables, *message-broker-variables, *database-variables ]
      BACKBASE_SECURITY_CSRF_ENABLED: "false"
      BUILDINGBLOCKS_SECURITY_CSRF_ENABLED: "false"
      LOGGING_LEVEL_COM_BACKBASE: "DEBUG"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "WARN"
      LOGGING_LEVEL_ROOT: "WARN"
      SERVER_SHUTDOWN: "graceful"
      backbase.audit.emitting-events-enabled: "true"
      backbase.audit.indexedMetadata.userId: "User ID,External User ID,User,Username,Sender User ID,Recipient ID,Owner ID"
      backbase.audit.timeline.eventCategories.no-read: "Identity and Access,Device Management,Message Center,Employee Actions,Comments,Payments,Employee,Push,Email,RTC,SMS,Card Management,Personal Finance Management,Identity User Management"
      spring.datasource.url: "jdbc:mysql://mysql:3306/audit?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true"
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/serviceregistry" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - activemq
      - registry

  wiremock:
    image: wiremock/wiremock:2.32.0
    profiles:
      - with-mocks
    command:
      - --global-response-templating
      - --verbose
    volumes:
      - ./stubs:/home/wiremock

  postman-health-check:
    image: postman/newman
    command:
      run /etc/newman/postman_collection.json --environment="/etc/newman/postman_environment.json"
    volumes:
      -  ../../test/postman/HealthCheck_Local-Backend-Environment.postman_collection.json:/etc/newman/postman_collection.json
      -  ../../test/postman/Docker-Backend-Environment.postman_environment.json:/etc/newman/postman_environment.json
    depends_on:
      access-control:
        condition: service_healthy
      arrangement-manager:
        condition: service_healthy
      backbase-identity:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      token-converter:
        condition: service_healthy
      user-manager:
        condition: service_healthy

  retail-app:
    image: crreference914.azurecr.io/retail-usa:2025.07
    environment:
      AUTH_REALM: "retail"
      AUTH_URL: http://localhost:8180/auth/
      API_ROOT: http://localhost:9091/api/
      PORT: 9091
    ports:
      - "9091:9091"
    volumes:
      - ./nginx/api.conf:/nginx-config/server/15-api.conf
    links:
      - edge
      - backbase-identity

  employee-app:
#    image: repo.backbase.com/backbase-docker-releases/employee-app:2023.08-no-production/
    image: crreference914.azurecr.io/employee-app:2025.03.3-LTS
    environment:
      PORT: 8080
      AUTH_URL: http://localhost:8180/auth/
      API_ROOT: http://localhost:8080/api
      AUTH_REALM: "employee"
      AUTH_SCOPE: openids
      AUTH_CLIENT_ID: bb-web-client
      AUTH_LANDING_PAGE: select-context
      AUTH_REDIRECT_PAGE: redirect
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/api.conf:/nginx-config/server/15-api.conf
    links:
      - edge
      - backbase-identity

  event-bridge:
    image: repo.backbase.com/backbase-docker-releases/event-bridge:2025.09.7-LTS
    ports:
      - "9094:8090"
    environment:
      BACKBASE_ENABLE_NO_AUTH_LOCALHOST_ENDPOINTS: "true"
      BACKBASE_SECURITY_CSRF_ENABLED: "false"
      BACKBASE_SECURITY_MTLS_ENABLED: "false"
      BUILDINGBLOCKS_SECURITY_CSRF_ENABLED: "false"
      EUREKA_CLIENT_ENABLED: "false"
      INSTALLATION: "reference"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=45 -Djava.security.egd=file:/dev/urandom -XX:+CrashOnOutOfMemoryError -XX:+AlwaysPreTouch -XX:InitialRAMPercentage=45 -XX:SurvivorRatio=30 -XX:NewRatio=1 -XX:C1MaxInlineLevel=18 -XX:C1MaxInlineSize=102 -XX:MaxInlineLevel=30 -XX:MaxInlineSize=102"
      LOGGING_LEVEL_COM_BACKBASE: "WARN"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "WARN"
      LOGGING_LEVEL_ROOT: "WARN"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus"
      MANAGEMENT_METRICS_TAGS_APPLICATION: "event-bridge"
      MANAGEMENT_SECURITY_ROLES: "ACTUATOR,USER"
      RELEASE_NAME: "event-bridge"
      SERVER_PORT: "8090"
      SERVER_SHUTDOWN: "graceful"
      SERVER_TOMCAT_MBEANREGISTRY_ENABLED: "true"
      SPRING_LIQUIBASE_ENABLED: "false"
      SPRING_MAIN_CLOUDPLATFORM: "KUBERNETES"
      SPRING_PROFILES_INCLUDE: "json-logging"
      backbase.lifecycle.delayed-shutdown.delay: "15s"
      backbase.lifecycle.delayed-shutdown.enabled: "true"
      management.metrics.distribution.percentiles: "0.95, 0.99, 1"
      management.metrics.distribution.percentiles.domain.service: "0.95, 0.99, 1"
      management.metrics.distribution.percentiles.hikaricp.connections: "0.95, 0.99, 1"
      management.metrics.distribution.percentiles.http.client.requests: "0.95, 0.99, 1"
      management.metrics.distribution.percentiles.http.server.requests: "0.95, 0.99, 1"
      management.metrics.distribution.percentiles.spring.data.repository.invocations: "0.95, 0.99, 1"
      management.metrics.distribution.sla.http.client.requests: "30ms,250ms,1000ms"
      management.metrics.distribution.sla.http.server.requests: "30ms,250ms,1000ms"
      management.security.roles: "ACTUATOR,USER"
      resilience4j.bulkhead.metrics.enabled: "true"
      resilience4j.bulkhead.metrics.legacy.enabled: "true"
      resilience4j.circuitbreaker.metrics.enabled: "true"
      resilience4j.circuitbreaker.metrics.legacy.enabled: "true"
      resilience4j.ratelimiter.metrics.enabled: "true"
      resilience4j.ratelimiter.metrics.legacy.enabled: "true"
      resilience4j.retry.metrics.enabled: "true"
      resilience4j.retry.metrics.legacy.enabled: "true"
      resilience4j.thread-pool-bulkhead.metrics.enabled: "true"
      resilience4j.thread-pool-bulkhead.metrics.legacy.enabled: "true"
      resilience4j.timelimiter.metrics.enabled: "true"
      resilience4j.timelimiter.metrics.legacy.enabled: "true"
      spring.cloud.azure.eventhubs.kafka.enabled: "false"
      spring.cloud.stream.binders.servicebus.environment.spring.main.sources: "com.azure.spring.cloud.stream.binder.servicebus.implementation.config.ServiceBusBinderConfiguration"
      spring.lifecycle.timeout-per-shutdown-phase: "50s"
      spring_cloud_stream_binders_servicebus_environment_spring_main_sources: "com.azure.spring.cloud.stream.binder.servicebus.implementation.config.ServiceBusBinderConfiguration"
    volumes:
      - ./exe/HealthCheck.jar:/tmp/HealthCheck.jar
      # - ./jwt/keystore_pub.p12:/jwt/public/keystore_pub.p12:ro # Uncomment if needed
    healthcheck:
      test: [ "CMD", "java", "-jar", "-Xms5M", "-Xmx10M", "/tmp/HealthCheck.jar", "http://localhost:8080/actuator/health/liveness" ]
      interval: 15s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    profiles:
      - observable
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    profiles:
      - observable
    volumes:
      - ./monitor/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

secrets:
  mvnrepo:
    file: ${HOME}/.m2/settings.xml
  mvnrepokey:
    file: ${HOME}/.m2/settings-security.xml # Optional: In case your maven credentials are encrypted with `mvn --encrypt-password`
