bootstrap:
  # Used by product-catalog-task
  productCatalog:
    productTypes:
      - productKindName: "currentAccount"
        productTypeName: "current-account"
        typeName: "Current Account"
        externalProductKindId: "kind1"
        externalProductId: "current-account"
      - productKindName: "savingsAccount"
        productTypeName: "savings-account"
        typeName: "Savings Accounts"
        externalProductKindId: "kind2"
        externalProductId: "savings-account"
  # Used by legal-entity-bootstrap-task
  legalEntity:
    name: "Moustache Bank"
    realmName: "backbase"
    externalId: "moustache-bank"
    legalEntityType: "BANK"
    referenceJobRoles:
      - name: "Entitlements - Manager"
        description: "Full Entitlements administration."
        functionGroups:
          - name: "Manage Entitlements"
            functions:
              - functionId: "5000"
                name: "Manage Case Definitions"
                privileges:
                  - privilege: "view"
                  - privilege: "execute"
              - functionId: "5001"
                name: "Manage Case Instances"
                privileges:
                  - privilege: "view"
              - functionId: "1019"
                name: "Manage Data Groups"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1020"
                name: "Manage Function Groups"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1010"
                name: "Manage Users"
                privileges:
                  - privilege: "view"
              - functionId: "1009"
                name: "Assign Permissions"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1028"
                name: "Manage Service Agreements"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1119"
                name: "Manage Self-approve Permissions"
                privileges:
                  - privilege: "view"
              - functionId: "1007"
                name: "Assign Users"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1035"
                name: "Manage User Profiles"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
              - functionId: "1011"
                name: "Manage Legal Entities"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1034"
                name: "Manage Identities"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1049"
                name: "Lock User"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1050"
                name: "Unlock User"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1084"
                name: "Revoke access"
                privileges:
                  - privilege: "create"
      - name: "Retail User"
        description: "Retail User Permissions"
        functionGroups:
          - name: "Products and Profile"
            functions:
              - functionId: "5000"
                name: "Manage Case Definitions"
                privileges:
                  - privilege: "view"
                  - privilege: "execute"
              - functionId: "5001"
                name: "Manage Case Instances"
                privileges:
                  - privilege: "view"
              - functionId: "1006"
                name: "Product Summary"
                functionCode: "product.summary"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
              - functionId: "1035"
                name: "Manage User Profiles"
                functionCode: "manage.user.profiles"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
    users:
      - user:
          externalId: "admin"
          fullName: "Backbase Root Admin"
          identityLinkStrategy: "CREATE_IN_IDENTITY"
          emailAddress:
            address: "bbadmin@email.com"
          mobileNumber:
            number: "1234567890"
        referenceJobRoleNames:
          - "Entitlements - Manager"
    productGroups:
      - name: "my-case-def-group"
        productGroupType: "CASE_DEFINITION"
        description: "My case definitions"
        customDataGroupItems:
          - internalId: "my-case-def"
        users:
          - user:
              externalId: "admin"
              fullName: "Backbase Root Admin"
              identityLinkStrategy: "CREATE_IN_IDENTITY"
              emailAddress:
                address: "bbadmin@email.com"
              mobileNumber:
                number: "1234567890"
            referenceJobRoleNames:
              - "Entitlements - Manager"
      - name: "my-case-definitions"
        productGroupType: "CASE_DEFINITION"
        description: "My case definitions"
        customDataGroupItems:
          - internalId: "my-case-def"
        users:
          - user:
              externalId: "admin"
              fullName: "Backbase Root Admin"
              identityLinkStrategy: "CREATE_IN_IDENTITY"
              emailAddress:
                address: "bbadmin@email.com"
              mobileNumber:
                number: "1234567890"
            referenceJobRoleNames:
              - "Entitlements - Manager"
    subsidiaries:
      - name: "Moustache Bank USA"
        realmName: "backbase"
        externalId: "moustache-bank-usa"
        legalEntityType: "BANK"
        productGroups:
          - name: "my-employee-case-definitions"
            productGroupType: "CASE_DEFINITION"
            description: "My employee case definitions"
            customDataGroupItems:
              - internalId: "my-case-def"
            users:
              - user:
                  externalId: "employee"
                  fullName: "Backbase Root Employee"
                  identityLinkStrategy: "CREATE_IN_IDENTITY"
                  emailAddress:
                    address: "bbemployee@email.com"
                  mobileNumber:
                    number: "1234567890"
                referenceJobRoleNames:
                  - "Entitlements - Employee"
        users:
          - user:
              externalId: "employee"
              fullName: "Backbase Root Employee"
              identityLinkStrategy: "CREATE_IN_IDENTITY"
              emailAddress:
                address: "bbemployee@email.com"
              mobileNumber:
                number: "1234567890"
            referenceJobRoleNames:
              - "Entitlements - Employee"
        referenceJobRoles:
          - name: "Entitlements - Employee"
            description: "Employee Entitlements employee."
            functionGroups:
              - name: "Manage Employee Entitlements"
                functions:
                  - functionId: "5000"
                    name: "Manage Case Definitions"
                    privileges:
                      - privilege: "view"
                      - privilege: "execute"
                  - functionId: "5001"
                    name: "Manage Case Instances"
                    privileges:
                      - privilege: "view"
        subsidiaries:
          - name: "Niels"
            realmName: "backbase"
            externalId: "niels"
            legalEntityType: "CUSTOMER"
            users:
              - user:
                  externalId: "niels"
                  fullName: "Niels"
                  identityLinkStrategy: "CREATE_IN_IDENTITY"
                  emailAddress:
                    address: "niels@email.com"
                  mobileNumber:
                    number: "1234567890"
            productGroups:
              - name: "my-case-instances"
                productGroupType: "CASE_INSTANCE"
                description: "My case instances"
                customDataGroupItems:
                  - internalId: "559deb8c1ac84f7dbba2a8986f1eea6b"
                users:
                  - user:
                      externalId: "niels"
                      fullName: "Niels"
                      identityLinkStrategy: "CREATE_IN_IDENTITY"
                      emailAddress:
                        address: "niels@email.com"
                      mobileNumber:
                        number: "1234567890"
                    referenceJobRoleNames:
                      - "Retail User"
          - name: "Sara"
            realmName: "backbase"
            externalId: "sara"
            legalEntityType: "CUSTOMER"
            users:
              - user:
                  externalId: "sara"
                  fullName: "Sara Jones"
                  identityLinkStrategy: "CREATE_IN_IDENTITY"
                  emailAddress:
                    address: "sara@email.com"
                  mobileNumber:
                    number: "1234567890"
            productGroups:
              - name: "sara-arrangements"
                users:
                  - user:
                      externalId: "sara"
                      fullName: "Sara Jones"
                      identityLinkStrategy: "CREATE_IN_IDENTITY"
                      emailAddress:
                        address: "sara@email.com"
                      mobileNumber:
                        number: "1234567890"
                    referenceJobRoleNames:
                      - "Retail User"